name: Build and Deploy to K3s

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, lab, AMD64]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image (AMD64 only)
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        no-cache: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/mon-site:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/mon-site:${{ github.sha }}

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Check cluster connection
      run: kubectl cluster-info

    - name: Deploy to K3s (use latest)
      run: |
        kubectl rollout restart deployment/mon-site-deploy -n default
